### ISSUE TITLE
Default behaviour for 403 answer seems to be DoS of the API

### ISSUE THREAD

**Issue by IvanVas** [zytedata/zyte-autoextract#40]
By default, if the client gets 403 from the API it continues to retry. This can create unnecessary load on the API.

Relevant code: https://github.com/zytedata/zyte-autoextract/blob/4813341e90f46581a2df2527037c075330ca3fb9/autoextract/__main__.py#L53

**Comment by BurnzZ** [comment]
After some offline discussions, it would seem that the Request-level errors aren't retried: https://github.com/zytedata/zyte-autoextract/blob/master/autoextract/aio/retry.py#L44-L48
